<?php
require_once __DIR__ . '/includes/config.php';

if (session_status() === PHP_SESSION_NONE) session_start();

$configured = is_file(__DIR__ . '/includes/local-config.php');
$success = false;
$error = '';

function kj_setup_run_sql(PDO $pdo, string $file): void {
    $sql = file_get_contents($file);
    if ($sql === false) throw new RuntimeException('Could not read ' . basename($file));
    $sql = preg_replace('/^\s*--.*$/m', '', $sql);
    foreach (preg_split('/;\s*(?:\r?\n|$)/', $sql) as $statement) {
        $statement = trim($statement);
        if ($statement !== '') $pdo->exec($statement);
    }
}

if (empty($_SESSION['setup_csrf'])) $_SESSION['setup_csrf'] = bin2hex(random_bytes(24));

if ($_SERVER['REQUEST_METHOD'] === 'POST' && !$configured) {
    try {
        if (!hash_equals($_SESSION['setup_csrf'], $_POST['csrf'] ?? '')) {
            throw new RuntimeException('The setup session expired. Refresh the page and try again.');
        }

        $host = trim($_POST['host'] ?? '127.0.0.1');
        $port = (int) ($_POST['port'] ?? 3306);
        $adminUser = trim($_POST['admin_user'] ?? 'root');
        $adminPass = (string) ($_POST['admin_password'] ?? '');
        $appUser = trim($_POST['app_user'] ?? 'kinyinya_app');
        $appPass = (string) ($_POST['app_password'] ?? 'kinyinya_dev_password');

        if (!preg_match('/^[A-Za-z0-9_]+$/', $appUser)) {
            throw new RuntimeException('The application username may contain only letters, numbers, and underscores.');
        }
        if ($port < 1 || $port > 65535 || $host === '' || $adminUser === '' || $appPass === '') {
            throw new RuntimeException('Complete all required database fields.');
        }

        $admin = new PDO("mysql:host={$host};port={$port};charset=utf8mb4", $adminUser, $adminPass, [
            PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION,
            PDO::ATTR_EMULATE_PREPARES => false,
        ]);

        kj_setup_run_sql($admin, __DIR__ . '/database/schema.sql');
        $quotedUser = '`' . str_replace('`', '``', $appUser) . '`';
        $quotedPassword = $admin->quote($appPass);
        $admin->exec("CREATE USER IF NOT EXISTS '{$appUser}'@'localhost' IDENTIFIED BY {$quotedPassword}");
        $admin->exec("ALTER USER '{$appUser}'@'localhost' IDENTIFIED BY {$quotedPassword}");
        $admin->exec("GRANT ALL PRIVILEGES ON kinyinya_jobs.* TO '{$appUser}'@'localhost'");
        $admin->exec('FLUSH PRIVILEGES');

        if (!empty($_POST['demo_data'])) {
            kj_setup_run_sql($admin, __DIR__ . '/database/seed.sql');
        }

        $settings = [
            'DB_HOST' => $host,
            'DB_PORT' => (string) $port,
            'DB_NAME' => 'kinyinya_jobs',
            'DB_USER' => $appUser,
            'DB_PASS' => $appPass,
        ];
        $contents = "<?php\n// Generated by setup.php. Keep this file private and do not commit it.\nreturn " . var_export($settings, true) . ";\n";
        if (file_put_contents(__DIR__ . '/includes/local-config.php', $contents, LOCK_EX) === false) {
            throw new RuntimeException('The database was created, but includes/local-config.php could not be written. Check folder permissions.');
        }
        $configured = true;
        $success = true;
        unset($_SESSION['setup_csrf']);
    } catch (Throwable $exception) {
        $error = $exception->getMessage();
    }
}
?>
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Set up Kinyinya Jobs</title>
  <link rel="stylesheet" href="<?= htmlspecialchars(kj_url('assets/style.css')) ?>">
</head>
<body>
<main class="wrap" style="max-width:760px; padding-top:36px;">
  <section class="pagehead">
    <p class="eyebrow">One-time installation</p>
    <h1>Set up Kinyinya Jobs</h1>
    <p>Connect to MySQL, create the database and a dedicated application account, and optionally load demonstration data.</p>
  </section>

  <?php if ($success): ?>
    <div class="flash">Setup completed successfully. The application is ready.</div>
    <p><a class="btn btn-primary" href="<?= htmlspecialchars(kj_url('index.php')) ?>">Open Kinyinya Jobs</a></p>
  <?php elseif ($configured): ?>
    <div class="flash">This copy is already configured.</div>
    <p><a class="btn btn-primary" href="<?= htmlspecialchars(kj_url('index.php')) ?>">Open Kinyinya Jobs</a></p>
    <p style="color:var(--ink-soft)">To configure a different database, remove <code>includes/local-config.php</code> and return to this page.</p>
  <?php else: ?>
    <?php if ($error): ?><div class="flash" style="background:var(--brick-100); color:var(--brick-600); border-color:var(--brick-600)"><?= htmlspecialchars($error) ?></div><?php endif; ?>
    <form method="post" class="card">
      <input type="hidden" name="csrf" value="<?= htmlspecialchars($_SESSION['setup_csrf']) ?>">
      <h3>MySQL administrator connection</h3>
      <p style="color:var(--ink-soft); margin-top:0">For XAMPP, the username is usually <strong>root</strong> with an empty password. For MySQL Workbench, enter the root password saved for your local connection.</p>
      <div class="grid-2">
        <div class="field"><label for="host">Server</label><input id="host" name="host" required value="<?= htmlspecialchars($_POST['host'] ?? '127.0.0.1') ?>"></div>
        <div class="field"><label for="port">Port</label><input id="port" name="port" type="number" required value="<?= htmlspecialchars($_POST['port'] ?? '3306') ?>"></div>
      </div>
      <div class="grid-2">
        <div class="field"><label for="admin_user">Administrator username</label><input id="admin_user" name="admin_user" required value="<?= htmlspecialchars($_POST['admin_user'] ?? 'root') ?>"></div>
        <div class="field"><label for="admin_password">Administrator password</label><input id="admin_password" name="admin_password" type="password" autocomplete="current-password"></div>
      </div>

      <h3>Application database account</h3>
      <div class="grid-2">
        <div class="field"><label for="app_user">Application username</label><input id="app_user" name="app_user" required value="<?= htmlspecialchars($_POST['app_user'] ?? 'kinyinya_app') ?>"></div>
        <div class="field"><label for="app_password">Application password</label><input id="app_password" name="app_password" type="password" required value="<?= htmlspecialchars($_POST['app_password'] ?? 'kinyinya_dev_password') ?>"></div>
      </div>
      <div class="field"><label><input name="demo_data" type="checkbox" value="1" checked style="width:auto"> Load demonstration employers, seekers, jobs, and applications</label></div>
      <button class="btn btn-primary" type="submit">Create database and finish setup</button>
    </form>
  <?php endif; ?>
</main>
</body>
</html>
